# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apaterno',
            new_name='apellidos',
        ),
    ]
