# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20170504_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biblioteca',
            field=models.ManyToManyField(blank=True, to='Books.Book'),
        ),
    ]
