# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('fecha_publicacio', models.DateField(null=True)),
                ('foto_portada', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('genero_literario', models.CharField(choices=[('DR', 'Drama'), ('CM', 'Comedia'), ('FT', 'Fantasia'), ('CF', 'Ciencia Ficción'), ('PS', 'Poesia'), ('LC', 'Literatura Contemporanea'), ('LH', 'Literatura Hispana'), ('LU', 'Literatura Universal'), ('HS', 'Historica')], max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authors.Author')),
            ],
        ),
    ]
