# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20170505_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='Authors.Author'),
        ),
    ]
